# -*- coding: utf-8 -*-
"""Problem_B4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CZl75SmW83Hpx-thdPzVxr4NhYtuIVp5
"""

!pip install scikit-learn tensorflow pandas
!pip install keras
!pip install keras-preprocessing

from sklearn.model_selection import train_test_split
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
import tensorflow as tf
import pandas as pd
import numpy as np

class MyCallbacks(tf.keras.callbacks.Callback):
    def on_epoch_end(self, epoch, logs=None):
        if (logs.get('val_accuracy') > 0.91 and logs.get('accuracy') > 0.91):
            print('\n Training is done, val is filled')
            self.model.stop_training = True

def solution_B4():
    bbc = pd.read_csv('https://github.com/dicodingacademy/assets/raw/main/Simulation/machine_learning/bbc-text.csv')

    # DO NOT CHANGE THIS CODE
    # Make sure you used all of these parameters or you can not pass this test
    vocab_size = 1000
    embedding_dim = 16
    max_length = 120
    trunc_type = 'post'
    padding_type = 'post'
    oov_tok = "<OOV>"
    training_portion = .8

    # YOUR CODE HERE
    #make list first
    sentences = []
    labels = []

    for index, row in bbc.iterrows():
        labels.append(row[0])
        sentences.append(row[1])

    training_size = int(len(sentences) * training_portion)

    # Using "shuffle=False"
    training_sentences, validation_sentences = train_test_split(sentences, train_size=training_size, shuffle=False) #YOUR CODE HERE
    training_labels, validation_labels = train_test_split(labels, train_size=training_size, shuffle=False) #YOUR CODE HERE

    # Fit your tokenizer with training data
    tokenizer = Tokenizer(num_words =vocab_size, oov_token =oov_tok) # YOUR CODE HERE

    #tokenizer
    tokenizer.fit_on_texts(training_sentences)

    #generate pad
    training_sequences = tokenizer.texts_to_sequences(training_sentences)
    training_padded = pad_sequences(training_sequences, maxlen=max_length, padding=padding_type, truncating=trunc_type)

    #generate pad
    testing_sequences = tokenizer.texts_to_sequences(validation_sentences)
    testing_padded = pad_sequences(testing_sequences, maxlen=max_length, padding=padding_type, truncating=trunc_type)

    training_labels = np.array(training_labels)
    testing_labels = np.array(validation_labels)

    # You can also use Tokenizer to encode your label.
    label_token = Tokenizer()
    label_token.fit_on_texts(labels)

    train_label_seq = np.array(label_token.texts_to_sequences(training_labels))
    testing_label_seq = np.array(label_token.texts_to_sequences(validation_labels))

    #modelliing
    model = tf.keras.Sequential([
        # YOUR CODE HERE.
        # YOUR CODE HERE. DO not change the last layer or test may fail
        tf.keras.layers.Embedding(input_dim=vocab_size, output_dim=embedding_dim, input_length=max_length),
        tf.keras.layers.GlobalAveragePooling1D(),
        tf.keras.layers.Dropout(0.2),
        tf.keras.layers.Dense(32, activation='relu'),
        tf.keras.layers.Dense(6, activation='softmax')
    ])

    # Make sure you are using "sparse_categorical_crossentropy" as a loss fuction
    #compiling
    model.compile(loss='sparse_categorical_crossentropy',optimizer=tf.keras.optimizers.Adam(learning_rate=0.001),metrics=['accuracy'])

    #callback
    callbacks = MyCallbacks()

    #training model
    model.fit(training_padded, train_label_seq, epochs=50, validation_data=(testing_padded, testing_label_seq), callbacks=[callbacks])
    return model

    # The code below is to save your model as a .h5 file.
    # It will be saved automatically in your Submission folder.
if __name__ == '__main__':
    # DO NOT CHANGE THIS CODE
    model = solution_B4()
    model.save("model_B4.h5")